AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Task App

Globals:
  Function:
    Timeout: 3

Resources:
  Table:
    Type: AWS::Serverless::SimpleTable

  ListTasksFunction:
    Type: AWS::Serverless::Function
    Connectors:
      TableConnector:
        Properties:
          Destination:
            Id: Table
          Permissions:
            - Read
    Properties:
      CodeUri: list_tasks
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tasks
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref Table

Outputs:
  Api:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks
