AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Task App

Globals:
  Function:
    Timeout: 3

Resources:
  TaskTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Tasks

  ListTasksFunction:
    Type: AWS::Serverless::Function
    Connectors:
      TaskTableConnector:
        Properties:
          Destination:
            Id: TaskTable
          Permissions:
            - Read
    Properties:
      CodeUri: list_tasks
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tasks
            Method: get
    Metadata:
      SamResourceId: list_tasks

Outputs:
  Api:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks
