AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Task App

Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Timeout: 3

Resources:
  Table:
    Type: AWS::Serverless::SimpleTable

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  ListTasksFunction:
    Type: AWS::Serverless::Function
    Connectors:
      TableConnector:
        Properties:
          Destination:
            Id: Table
          Permissions:
            - Read
    Properties:
      CodeUri: list_tasks
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tasks
            Method: get
            RestApiId:
              Ref: Api
      Environment:
        Variables:
          TABLE_NAME: !Ref Table

  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Connectors:
      TableConnector:
        Properties:
          Destination:
            Id: Table
          Permissions:
            - Write
    Properties:
      CodeUri: create_task
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tasks
            Method: post
            RestApiId:
              Ref: Api
      Environment:
        Variables:
          TABLE_NAME: !Ref Table

  FrontendBucket:
    Type: AWS::S3::Bucket

  FrontendOac:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !GetAtt FrontendBucket.DomainName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - DomainName: !GetAtt FrontendBucket.DomainName
            Id: !GetAtt FrontendBucket.DomainName
            OriginAccessControlId: !GetAtt FrontendOac.Id
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: !GetAtt FrontendBucket.DomainName
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: 2008-10-17
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn:
                  - !Join
                    - ''
                    - - !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/'
                      - !Ref Distribution

Outputs:
  ApiEndpointUrl:
    Value:
      Fn::Sub: https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod/tasks
  FrontendUrl:
    Value: !GetAtt Distribution.DomainName
  FrontendBucketName:
    Value: !Ref FrontendBucket
